"""SQLAlchemy ORM models mapping to SQL Server Fraud Investigation database."""
from datetime import datetime
from decimal import Decimal
from typing import List

from sqlalchemy import (
    DECIMAL,
    ForeignKey,
    Sequence,
    Integer,
    DateTime,
    Boolean,
    Unicode,
    UnicodeText,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


# Sequence for risk_alert_id_seq (starts at 6000)
risk_alert_id_seq = Sequence("risk_alert_id_seq", schema="dbo")


class Customer(Base):
    """Represents a customer in the fraud investigation system."""

    __tablename__ = "customers"
    __table_args__ = {"schema": "dbo"}

    customer_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    customer_reference: Mapped[str] = mapped_column(Unicode(50), unique=True, nullable=False)
    first_name: Mapped[str] = mapped_column(Unicode(100), nullable=False)
    last_name: Mapped[str] = mapped_column(Unicode(100), nullable=False)
    email: Mapped[str] = mapped_column(Unicode(255), nullable=True)
    phone: Mapped[str] = mapped_column(Unicode(50), nullable=True)
    date_of_birth: Mapped[datetime] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    # Relationships
    transactions: Mapped[List["Transaction"]] = relationship(
        "Transaction", back_populates="customer", cascade="all, delete-orphan"
    )
    risk_alerts: Mapped[List["RiskAlert"]] = relationship(
        "RiskAlert", back_populates="customer", cascade="all, delete-orphan"
    )
    investigations: Mapped[List["Investigation"]] = relationship(
        "Investigation", back_populates="customer", cascade="all, delete-orphan"
    )


class Transaction(Base):
    """Represents a financial transaction."""

    __tablename__ = "transactions"
    __table_args__ = {"schema": "dbo"}

    transaction_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    customer_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("dbo.customers.customer_id"), nullable=False
    )
    business_transaction_id: Mapped[str] = mapped_column(Unicode(64), nullable=False)
    transaction_datetime: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    recorded_customer_reference: Mapped[str] = mapped_column(
        Unicode(50), nullable=True
    )
    amount: Mapped[Decimal] = mapped_column(DECIMAL(12, 2), nullable=False)
    merchant_name: Mapped[str] = mapped_column(Unicode(200), nullable=True)
    merchant_category: Mapped[str] = mapped_column(Unicode(100), nullable=True)
    channel: Mapped[str] = mapped_column(Unicode(50), nullable=True)
    location: Mapped[str] = mapped_column(Unicode(100), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # Relationships
    customer: Mapped["Customer"] = relationship("Customer", back_populates="transactions")
    risk_alerts: Mapped[List["RiskAlert"]] = relationship(
        "RiskAlert", back_populates="transaction", cascade="all, delete-orphan"
    )


class RiskAlert(Base):
    """Represents a fraud risk alert generated by analysis rules."""

    __tablename__ = "risk_alerts"
    __table_args__ = {"schema": "dbo"}

    alert_id: Mapped[int] = mapped_column(
        Integer, risk_alert_id_seq, primary_key=True
    )
    transaction_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("dbo.transactions.transaction_id"), nullable=False
    )
    customer_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("dbo.customers.customer_id"), nullable=False
    )
    analysis_key: Mapped[str] = mapped_column(
        Unicode(200), nullable=False, unique=True
    )
    alert_type: Mapped[str] = mapped_column(Unicode(50), nullable=False)
    risk_score: Mapped[int] = mapped_column(Integer, nullable=False)
    severity: Mapped[str] = mapped_column(Unicode(20), nullable=False)
    alert_status: Mapped[str] = mapped_column(Unicode(20), nullable=False, default="OPEN")
    rule_evidence: Mapped[str] = mapped_column(UnicodeText, nullable=False)
    notes: Mapped[str] = mapped_column(Unicode(500), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # Relationships
    transaction: Mapped["Transaction"] = relationship("Transaction", back_populates="risk_alerts")
    customer: Mapped["Customer"] = relationship("Customer", back_populates="risk_alerts")
    investigations: Mapped[List["Investigation"]] = relationship(
        "Investigation", back_populates="risk_alert", cascade="all, delete-orphan"
    )


class Investigation(Base):
    """Represents an investigation opened due to a risk alert."""

    __tablename__ = "investigations"
    __table_args__ = {"schema": "dbo"}

    investigation_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    alert_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("dbo.risk_alerts.alert_id"), nullable=True
    )
    customer_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("dbo.customers.customer_id"), nullable=False
    )
    investigation_status: Mapped[str] = mapped_column(Unicode(20), nullable=False)
    priority: Mapped[str] = mapped_column(Unicode(20), nullable=False)
    assigned_to: Mapped[str] = mapped_column(Unicode(100), nullable=True)
    summary: Mapped[str] = mapped_column(Unicode(500), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # Relationships
    risk_alert: Mapped["RiskAlert"] = relationship("RiskAlert", back_populates="investigations")
    customer: Mapped["Customer"] = relationship("Customer", back_populates="investigations")
